package Model;
// Generated 2020�~11��13�� �U��3:46:48 by Hibernate Tools 5.4.21.Final

import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer employeeId;
	private String employeeName;
	private String account;
	private String password;
	private String email;
	private Date createdDate;

	public Employee() {
	}

	public Employee(String account, String password) {
		super();
		this.account = account;
		this.password = password;
	}

	public Employee(Integer employeeId, String employeeName, String account, String password, String email, Date createdDate) {
		super();
		this.employeeId = employeeId;
		this.employeeName = employeeName;
		this.account = account;
		this.password = password;
		this.email = email;
		this.createdDate = createdDate;
	}

	public Employee(String employeeName, String account, String password, String email, Date createdDate) {
		this.employeeName = employeeName;
		this.account = account;
		this.password = password;
		this.email = email;
		this.createdDate = createdDate;
	}

	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
