package Model;

import java.util.HashSet;
import java.util.Set;

/**
 * Lesson generated by hbm2java
 */
public class Lesson implements java.io.Serializable {

	private Integer lessonId;
	private String lessonName;
	private String lessonDescription;
	private String lessonPrice;
	private String lessonDate;
	private String lessonPicUrl;

	public Lesson() {
	}

	public Lesson(Integer lessonId, String lessonName, String lessonDescription, String lessonPrice, String lessonDate,
			String lessonPicUrl) {
		super();
		this.lessonId = lessonId;
		this.lessonName = lessonName;
		this.lessonDescription = lessonDescription;
		this.lessonPrice = lessonPrice;
		this.lessonDate = lessonDate;
		this.lessonPicUrl = lessonPicUrl;
	}

	public Lesson(Integer lessonId, String lessonName, String lessonDescription, String lessonPrice, String lessonDate) {
		super();
		this.lessonId = lessonId;
		this.lessonName = lessonName;
		this.lessonDescription = lessonDescription;
		this.lessonPrice = lessonPrice;
		this.lessonDate = lessonDate;
	}

	public Lesson(String lessonName, String lessonDescription, String lessonPrice, String lessonDate,
			String lessonPicUrl) {
		this.lessonName = lessonName;
		this.lessonDescription = lessonDescription;
		this.lessonPrice = lessonPrice;
		this.lessonDate = lessonDate;
		this.lessonPicUrl = lessonPicUrl;
		
	}

	public Integer getLessonId() {
		return this.lessonId;
	}

	public void setLessonId(Integer lessonId) {
		this.lessonId = lessonId;
	}

	public String getLessonName() {
		return this.lessonName;
	}

	public void setLessonName(String lessonName) {
		this.lessonName = lessonName;
	}

	public String getLessonDescription() {
		return this.lessonDescription;
	}

	public void setLessonDescription(String lessonDescription) {
		this.lessonDescription = lessonDescription;
	}

	public String getLessonPrice() {
		return this.lessonPrice;
	}

	public void setLessonPrice(String lessonPrice) {
		this.lessonPrice = lessonPrice;
	}

	public String getLessonDate() {
		return this.lessonDate;
	}

	public void setLessonDate(String lessonDate) {
		this.lessonDate = lessonDate;
	}

	public String getLessonPicUrl() {
		return this.lessonPicUrl;
	}

	public void setLessonPicUrl(String lessonPicUrl) {
		this.lessonPicUrl = lessonPicUrl;
	}


}
