package Model;

import java.util.Date;

/**
 * Lessonsignup generated by hbm2java
 */
public class Lessonsignup implements java.io.Serializable {

	private Integer lessonSignUpId;
	private Integer lessonId;
	private String name;
	private String phoneNumber;
	private String email;
	private Integer memberId;
	private Date createdDate;
	
	public Lessonsignup() {
	}

	public Lessonsignup(Integer lessonSignUpId, Integer lessonId, String name, String phoneNumber, String email, Date createdDate) {
		super();
		this.lessonSignUpId = lessonSignUpId;
		this.lessonId = lessonId;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.memberId = memberId;
		this.createdDate = createdDate;
	}

	public Lessonsignup(Integer lessonId, String name, String phoneNumber, String email, Integer memberId, Date createdDate) {
		this.lessonId = lessonId;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.memberId = memberId;
		this.createdDate = createdDate;
	}

	public Integer getLessonSignUpId() {
		return this.lessonSignUpId;
	}

	public void setLessonSignUpId(Integer lessonSignUpId) {
		this.lessonSignUpId = lessonSignUpId;
	}

	public Integer getLessonId() {
		return this.lessonId;
	}

	public void setLessonId(Integer lessonId) {
		this.lessonId = lessonId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}
	
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
