package Model;
// Generated 2020�~11��13�� �U��3:46:48 by Hibernate Tools 5.4.21.Final

/**
 * Orderdetail generated by hbm2java
 */
public class Orderdetail implements java.io.Serializable {

	private Integer orderdetailId;
	private Integer orderNumber;
	private Integer productCode;
	private Integer quantity;
	private Integer price;

	public Orderdetail() {
	}

	public Orderdetail(Integer orderdetailId, Integer orderNumber, Integer productCode, Integer quantity,
			Integer price) {
		super();
		this.orderdetailId = orderdetailId;
		this.orderNumber = orderNumber;
		this.productCode = productCode;
		this.quantity = quantity;
		this.price = price;
	}

	public Orderdetail(Integer orderNumber, Integer productCode, Integer quantity, Integer price) {
		this.orderNumber = orderNumber;
		this.productCode = productCode;
		this.quantity = quantity;
		this.price = price;
	}

	public Integer getOrderdetailId() {
		return this.orderdetailId;
	}

	public void setOrderdetailId(Integer orderdetailId) {
		this.orderdetailId = orderdetailId;
	}

	public Integer getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(Integer orderNumber) {
		this.orderNumber = orderNumber;
	}

	public Integer getProductCode() {
		return this.productCode;
	}

	public void setProductCode(Integer productCode) {
		this.productCode = productCode;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

}
