package Model;
// Generated 2020�~11��13�� �U��3:46:48 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Orderlist generated by hbm2java
 */
public class Orderlist implements java.io.Serializable {

	private Integer orderNumber;
	private Integer memberId;
	private String orderDate;
	private Set<Orderdetail> orderdetails = new HashSet<Orderdetail>(0);

	public Orderlist() {
	}

	public Orderlist(Integer memberId, String orderDate, Set<Orderdetail> orderdetails) {
		this.memberId = memberId;
		this.orderDate = orderDate;
		this.orderdetails = orderdetails;
	}

	public Integer getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(Integer orderNumber) {
		this.orderNumber = orderNumber;
	}

	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	public String getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(String orderDate) {
		this.orderDate = orderDate;
	}

	public Set<Orderdetail> getOrderdetails() {
		return this.orderdetails;
	}

	public void setOrderdetails(Set<Orderdetail> orderdetails) {
		this.orderdetails = orderdetails;
	}

}
