package Model;
// Generated 2020�~11��13�� �U��3:46:48 by Hibernate Tools 5.4.21.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer productCode;
	private String productName;
	private String description;
	private Integer price;	
	private String expireDate;
	private String unitInStock;
	private Integer categoryId;
	private String picUrl;
	private Date createdDate;

	public Product() {
	}

	public Product(Integer productCode, String productName, String description, Integer price, Integer categoryId,
			String expireDate, String unitInStock, String picUrl, Date createdDate) {
		super();
		this.productCode = productCode;
		this.productName = productName;
		this.description = description;
		this.price = price;
		this.categoryId = categoryId;
		this.expireDate = expireDate;
		this.unitInStock = unitInStock;
		this.picUrl = picUrl;
		this.createdDate = createdDate;
	}

	public Product(String productName, String description, Integer price, Integer categoryId, String expireDate,
			String unitInStock, String picUrl, Date createdDate) {
		this.productName = productName;
		this.description = description;
		this.price = price;
		this.categoryId = categoryId;
		this.expireDate = expireDate;
		this.unitInStock = unitInStock;
		this.picUrl = picUrl;
		this.createdDate = createdDate;
		
	}

	public Integer getProductCode() {
		return this.productCode;
	}

	public void setProductCode(Integer productCode) {
		this.productCode = productCode;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(String expireDate) {
		this.expireDate = expireDate;
	}

	public String getUnitInStock() {
		return this.unitInStock;
	}

	public void setUnitInStock(String unitInStock) {
		this.unitInStock = unitInStock;
	}

	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
